#!/usr/bin/env bash
set -euo pipefail

# Demo Two: start at pickup, call passenger immediately, then reroute to a fixed second destination.

export SCENARIO="${SCENARIO:-reroute_request}"
export SCENARIO_SPAWN_INDEX="${SCENARIO_SPAWN_INDEX:-5}"
export SCENARIO_REROUTE_TARGET_INDEX="${SCENARIO_REROUTE_TARGET_INDEX:-0}"
export SCENARIO_REROUTE_FORWARD_METERS="${SCENARIO_REROUTE_FORWARD_METERS:-65}"
export SCENARIO_ARRIVAL_DISTANCE="${SCENARIO_ARRIVAL_DISTANCE:-2}"
export SCENARIO_CURB_OFFSET_FEET="${SCENARIO_CURB_OFFSET_FEET:-2}"
export SCENARIO_CURB_PULL_OVER_SECONDS="${SCENARIO_CURB_PULL_OVER_SECONDS:-8}"
export SCENARIO_CURB_STRAIGHTEN_SECONDS="${SCENARIO_CURB_STRAIGHTEN_SECONDS:-0}"
export SCENARIO_START_CURB_OFFSET_FEET="${SCENARIO_START_CURB_OFFSET_FEET:--21}"
export SCENARIO_WARMUP_FRAMES="${SCENARIO_WARMUP_FRAMES:-0}"
export DESTINATION_LABEL="${DESTINATION_LABEL:-the pickup location}"
export REROUTE_DESTINATION_LABEL="${REROUTE_DESTINATION_LABEL:-the alternate pickup point}"
export DEMO_REROUTE_TIMEOUT_SECONDS="${DEMO_REROUTE_TIMEOUT_SECONDS:-60}"
export DEMO_MODE="${DEMO_MODE:-false}"
export GEMINI_MODEL="${GEMINI_MODEL:-gemini-2.5-flash}"
export CAMERA_VIEW="${CAMERA_VIEW:-chase}"
export CAMERA_WIDTH="${CAMERA_WIDTH:-1920}"
export CAMERA_HEIGHT="${CAMERA_HEIGHT:-1080}"
export CAMERA_JPEG_QUALITY="${CAMERA_JPEG_QUALITY:-95}"
export SPECTATOR_UPDATE_HZ="${SPECTATOR_UPDATE_HZ:-30}"
export SPECTATOR_SMOOTHING="${SPECTATOR_SMOOTHING:-0.12}"
export SPECTATOR_DISTANCE="${SPECTATOR_DISTANCE:-10}"
export SPECTATOR_HEIGHT="${SPECTATOR_HEIGHT:-5}"
export SPECTATOR_PITCH="${SPECTATOR_PITCH:--16}"

exec ./run_live.sh "$@"
